version: '3.1'
services:
  auth:
    depends_on:
      - db
    image: node:12-alpine
    command: npm run dev
    working_dir: /auth
    volumes:
      - .:/auth
    ports:
      - 4000:4000
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://db:27017/foo

  db:
    image: mvertes/alpine-mongo
    working_dir: /app
    volumes:
      - ./db/:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
