version: '3.1'
services:
  auth:
    depends_on:
      - db
    image: node:12-alpine
    command: sh -c "npm run setup && npm run dev"
    working_dir: /auth
    volumes:
      - .:/auth
    ports:
      - 4000:4000
    networks:
      - foo
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/foo

  db:
    image: mvertes/alpine-mongo
    working_dir: /app
    volumes:
      - ./db/:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017

volumes:
  postgres_data:

networks:
  foo:
